[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyTGM"
version = "4.0.0"
description = "Terminal Game Maker"
readme = "README.txt"
license = { file = "LICENSE" }
authors = [
    { name = "Tokyn Blast", email = "tokynblast@gmail.com" }
]
maintainers = [
    { name = "Tokyn Blast", email = "tokynblast@gmail.com" }
]
keywords = ["game", "game maker", "terminal", "tools"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Operating System :: Microsoft :: Windows :: Windows 10 :: Linux",
    "License :: Other/Proprietary License",
    "Programming Language :: Python :: 3 :: Only"
]
dependencies = []

[project.urls]
Homepage = "https://youtube.tokynblast.space/programming/libraries/pytgm/init"

[project.optional-dependencies]
test = ["pytest"]

[tool.setuptools]
packages = ["find:"]

[tool.setuptools.extension]
"click" = { sources = ["click.c"] }

[project.requires-python]
">=3.13"

[project.scripts]
click = "pytgm.terd.click"
