[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyTGM"
version = "4.0.0"
description = "Terminal Game Maker"
long_description = file('README.txt').read() + '\n\n' + file('CHANGELOG.txt').read()
url = "https://youtube.tokynblast.space/programming/libraries/pytgm/init"
author = "Tokyn Blast"
author_email = "tokynblast@gmail.com"
maintainer = "Tokyn Blast"
maintainer_email = "tokynblast@gmail.com"
license = "Bspace"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Game Developers",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "License :: Bspace License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
]
keywords = ["game", "game maker", "terminal", "tools", "pytgm", "terminal input"]
packages = ["pytgm"]
install_requires = []

[project.ext_modules]
click = {
    sources = ["terd/click.c"],
    extra_compile_args = extra_compile_args[sys.platform],
}
