name: Compile C++

on:
  push:
    paths:
      - pytgm/**/*.cpp
      - .github/workflows/compile.yml
      - CMakeLists.txt
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip python3-dev cmake g++ 
          pip install pybind11 python3-dev pybind11-dev cmake ninja-build

      - name: Configure and Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
