name: Compile C++

on:
  push:
    paths:
      - pytgm/**/*.cpp
      - .github/workflows/compile.yml
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install g++
        run: sudo apt-get install g++

      - name: Install dependencies
        run: sudo apt-get install wheel pybind11 setuptools

      - name: Compile C++
        run: g++ -std=c++17 pytgm/**/*.cpp -o pytgm/pytgm