name: Compile C++

on:
  push:
    paths:
      - pyTGM/**/*.cpp
      - .github/workflows/compile.yml
      - CMakeLists.txt
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip python3-dev cmake g++ ninja-build
          pip install pybind11

      - name: Configure and Build
        run: |
          mkdir -p build
          cd build
          pybind11_DIR=$(python3 -m pybind11 --cmakedir)
          cmake -Dpybind11_DIR=${pybind11_DIR} ..
          cmake ..
          make -j $(nproc)
