name: Compile C++

on:
  push:
    paths:
      - pyTGM/**/*.cpp
      - pyTGM/**/*.hpp
      - pyTGM/**/*.pyx
      - .github/workflows/compile.yml
      - CMakeLists.txt
      - setup.py
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev cmake g++ ninja-build
          python -m pip install --upgrade pip
          pip install --upgrade Cython setuptools wheel

      - name: Clean build files
        run: |
          # Clean all Cython-generated files
          find pyTGM -type f \( -name "*.cpp" -o -name "*.c" -o -name "*.so" -o -name "*.html" \) -delete
          # Remove Python cache files
          find . -type d -name "__pycache__" -exec rm -rf {} +
          find . -type f -name "*.pyc" -delete
          # Clean build directories
          rm -rf build/ dist/ *.egg-info/

      - name: Configure and Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          cmake --build . --config Release -j $(nproc)
          cd ..
          python setup.py build_ext
