name: C++ Error Checking

on:
  push:
    paths:
      - pytgm/**
      - .github/workflows/cpplint.yml
    branches:
      - main

jobs:
  cpp-error-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck clang-tidy
        python -m pip install --upgrade pip
        python -m pip installpybind11

    - name: Run Cppcheck (Error Checking Only)
      run: |
        cppcheck --enable=warning,style,performance,portability --error-exitcode=1 .

    - name: Run Clang-Tidy (Error Checking Only)
      run: |
        clang-tidy **/*.cpp --checks=-*,bugprone-*,modernize-* --warnings-as-errors='*' -- -std=c++17