name: C++ Lint

on:
  push:
    paths:
      - pyTGM/**/*.cpp
      - .github/workflows/cpplint.yml
      - CMakeLists.txt
      - setup.py
    branches:
      - main

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy python3-dev cmake ninja-build python3-pip
          python3 -m pip install --upgrade pip
          python3 -m pip install nanobind

      - name: Configure Project and Generate compile_commands.json
        run: |
          mkdir -p build
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -GNinja .

      - name: Run clang-tidy on C++ files
        run: |
          cd build
          NANOBIND_INCLUDES=$(python3 -c "import nanobind; print(nanobind.include_dir())")
          PYTHON_INCLUDES=$(python3-config --includes | tr ' ' '\n' | grep "^-I" | sed 's/^-I//' | grep -v "/usr/include/python3.12")
          INCLUDE_ARGS=$(echo $PYTHON_INCLUDES | xargs -I{} echo --extra-arg="-I{}" | tr '\n' ' ')
          find ../pyTGM -type f \( -name '*.cpp' \) | xargs -I{} clang-tidy -p . {} \
            --extra-arg="-I$NANOBIND_INCLUDES" $INCLUDE_ARGS || true