name: C++ Lint

on:
  push:
    branches:
      - main
    paths:
      - pytgm/**

jobs:
  build:
    runs-on: ubuntu-latest
    container:
     image: python:3.11

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Cache
      run: |
        apt-cache search python3

    - name: Install Dependencies
      run: |
        apt-get update
        apt-get install -y libpython3.11-stdlib build-essential zlib1g-dev
        apt-get install -y clang-tidy build-essential cmake python3.11-dev
        python -m pip install --upgrade pip
        python -m pip install pybind11
         
    - name: Run clang-tidy
      run: |
        clang-tidy **/*.cpp --checks=-*,bugprone-*,modernize-*,-modernize-use-trailing-return-type,-clang-diagnostic-error,-clang-diagnostic-warning -- \
         -std=c++17 -I$(python -m pybind11 --includes) -ferror-limit=0
