name: C++ Lint

on:
  push:
    paths:
      - pyTGM/**/*.cpp
      - .github/workflows/cpplint.yml
      - CMakeLists.txt
    branches:
      - main

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy python3-dev pybind11-dev cmake ninja-build

      - name: Configure Project and Generate compile_commands.json
        run: |
          mkdir -p build && cd build
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -GNinja ..

      - name: Run clang-tidy on all C++ files
        run: |
          cd build
          find .. -type f \( -name '*.cpp' -o -name '*.cc' -o -name '*.cxx' \) | xargs clang-tidy -p .
