name: C++ Lint

on:
  push:
    branches:
      - main
    paths:
      - pytgm/**
      - .github/workflows/cpplint.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container:
     image: python:3.11

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        apt-get update
        apt-get install python3-dev
        python -m pip install --upgrade pip
        python -m pip install pybind11
         
    - name: Run clang-tidy
      run: |
        clang-tidy **/*.cpp --exclude-header-filter='.*/Python\.h$' <source_files>
