name: C++ Lint

on:
  push:
    paths:
      - pyTGM/**/*.cpp
      - pyTGM/**/*.hpp
      - .github/workflows/cpplint.yml
      - CMakeLists.txt
      - setup.py
    branches:
      - main

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy python3-dev cmake ninja-build cython3

      - name: Configure Project and Generate compile_commands.json
        run: |
          mkdir -p build && cd build
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -GNinja ..

      - name: cat/pwd test
        run: |
          pwd
          cat ./pyTGM/sound/sound.hpp

      - name: Run clang-tidy on C++ files
        run: |
          cd build
          find .. -type f \( -name '*.cpp' -o -name '*.hpp' \) | xargs clang-tidy -p .
