name: C++ Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
     image: python:3.13

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        apt-get update
        apt-get install -y clang-tidy build-essential cmake python3.13
        python -m pip install --upgrade pip
        python -m pip install pybind11
    - name: Run clang-tidy
      run: |
        clang-tidy **/*.cpp --checks=-*,bugprone-*,modernize-* --warnings-as-errors='*' -- -std=c++17 -I$(python -m pybind11 --includes)
