name: C++ Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy python3-dev pybind11-dev

      - name: Configure Project and Generate compile_commands.json
        run: |
          mkdir build && cd build
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..

      - name: Run clang-tidy
        run: |
          clang-tidy -p build $(find . -type f \( -name '*.cpp' -o -name '*.cc' -o -name '*.cxx' \))
