name: C++ Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
     image: python:3.11

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Cache
      run: |
        apt-cache search python3

    - name: Install Dependencies
      run: |
        apt-get update
        apt-get install -y build-essential wget zlib1g-dev libffi-dev libssl-dev
        wget https://www.python.org/ftp/python/3.11.6/Python-3.11.6.tgz
        tar -xf Python-3.11.6.tgz
        cd Python-3.11.6
        ./configure --enable-optimizations
        make -j$(nproc)
        make altinstall  # Prevents overwriting the system Python
        apt-get install -y clang-tidy build-essential cmake python3.11-dev
        python -m pip install --upgrade pip
        python -m pip install pybind11
         
    - name: Run clang-tidy
      run: |
        clang-tidy **/*.cpp --checks=-*,bugprone-*,modernize-*,-modernize-use-trailing-return-type -- -std=c++17 -I$(python -m pybind11 --includes)
