name: C++ Lint

on:
  push:
    branches:
      - main
    paths:
      - pytgm/**
      - .github/workflows/cpplint.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container:
     image: python:3.11

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        apt-get update
        apt-get install -y clang-tidy
        apt-get install -y python3-dev
        python -m pip install --upgrade pip
        python -m pip install pybind11
         
    - name: Run clang-tidy
      run: |
        clang-tidy $(find . -name '*.cpp') --header-filter=.*/Python\.h$'
