name: C++ Lint

on:
  push:
    branches:
      - main
    paths:
      - pytgm/**
      - .github/workflows/cpplint.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        export DEBIAN_FRONTEND=noninteractive
        echo 'tzdata tzdata/Areas select America' | debconf-set-selections
        echo 'tzdata tzdata/Zones/America select Los_Angeles' | debconf-set-selections
        apt-get update
        apt-get install -y tzdata python3.11-dev clang-tidy libpython3.11-dev
        python3.11 -m pip install --upgrade pip
        python3.11 -m pip install pybind11



    - name: Run clang-tidy
      run: |
        clang-tidy $(find . -name '*.cpp') --header-filter=.*/Python\.h$
