name: C++ Lint

on:
  push:
    branches:
      - main
    paths:
      - pytgm/**
      - .github/workflows/cpplint.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container:
     image: python:3.11

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: 3-dev

    - name: Install Dependencies
      run: |
        apt-get update
        python -m pip install --upgrade pip
        apt-get install -y clang-tidy
        python -m pip install pybind11
        apt-get install -y python3.11-dev
        apt-get install -y libpython3.11-dev

    - name: Run clang-tidy
      run: |
        clang-tidy $(find . -name '*.cpp') --header-filter=.*/Python\.h$
