name: C++ Lint

on:
  push:
    branches:
      - main
    paths:
      - pytgm/**
      - .github/workflows/cpplint.yml

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set Non-Interactive Mode
      run: |
        export DEBIAN_FRONTEND=noninteractive
        echo 'tzdata tzdata/Areas select America' | debconf-set-selections
        echo 'tzdata tzdata/Zones/America select Los_Angeles' | debconf-set-selections

    - name: Install Dependencies
      run: |
        apt-get update
        apt-get install -y tzdata python3.10 python3.10-dev clang-tidy libpython3.10-dev
        python3.10 -m pip install --upgrade pip
        python3.10 -m pip install pybind11

    - name: Run clang-tidy
      run: |
        clang-tidy $(find . -name '*.cpp') --header-filter=.*/Python\.h$
