name: Lint with Flake8
on:
  push:
    paths:
      - pytgm/**
      - setup.py
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install Flake8
        run: pip install flake8
      - name: Run Flake8
        run: flake8 *.py
