name: SHA-256 Generate and Update

on:
  push:
    paths:
      - pytgm/**
      - '!pytgm/__init__.py'
      - '!pytgm/graphics/__init__.py'
    branches:
      - main

jobs:
  generate-hashes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Parse JSON
        run: jq . VERSION.json

      - name: Generate SHA-256 hashes
        run: |
          # Find all Python files excluding __init__.py and tred/__init__.py
          find pytgm/ -type f -name '*.py' ! -name '__init__.py' ! -path 'pytgm/terd/*' -print0 | xargs -0 sha256sum > hashes.txt

          # Ensure VERSION.json exists and has the 'hashes' object
          if [ ! -f VERSION.json ]; then
            echo '{"hashes":{}}' > VERSION.json
          fi

          # Update VERSION.json with the new hashes
          while IFS= read -r line; do
            file=$(echo "$line" | cut -d' ' -f2- | xargs)
            hash=$(echo "$line" | cut -d' ' -f1)
            jq ".hashes[\"$file\"] = \"$hash\"" VERSION.json > VERSION.json.tmp && mv VERSION.json.tmp VERSION.json
          done < hashes.txt

          # Delete hashes.txt after it is used
          rm hashes.txt

      - name: Check for changes in VERSION.json
        run: |
          if git diff --quiet --exit-code; then
            echo "No changes to VERSION.json, skipping commit."
            exit 0
          fi

      - name: Commit and Push Changes
        env:
          HASHGEN: ${{ secrets.HASHGENERATE }}
        run: |
          git config --local user.name "TokynBlast"
          git config --local user.email "tokynblast@gmail.com"
          git remote set-url origin https://x-access-token:${HASHGEN}@github.com/TokynBlast/pyTGM.git
          git add VERSION.json
          git commit -m "Update SHA-256 hashes in VERSION.json"
          git push
