name: Generate SHA-3 Hashes and Update VERSION.json

on:
  push:
    branches:
      - main

jobs:
  generate-hashes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Install sha3sum
        run: |
          sudo apt-get update
          sudo apt-get install -y sha3sum jq

      - name: Generate SHA-3 hashes
        run: |
          sha3sum pytgm/board.py pytgm/b64.py pytgm/file.py pytgm/graphics.py pytgm/random.py pytgm/sound.py pytgm/terd/click.c pytgm/terd/geky.py > hashes.txt
          while IFS= read -r line; do
            file=$(echo $line | cut -d' ' -f2-)
            hash=$(echo $line | cut -d' ' -f1)
            jq ".hash[\"$file\"] = \"$hash\"" VERSION.json > VERSION.json.tmp && mv VERSION.json.tmp VERSION.json
          done < hashes.txt

      - name: Commit and Push Changes
        run: |
          git config --local user.name "Your Name"
          git config --local user.email "your.email@example.com"
          git add VERSION.json
          git commit -m "Update SHA-3 hashes in VERSION.json"
          git push
