name: Security Hashes

on:
  push:
    paths:
      - pyTGM/**
      - .github/workflows/generate-sha3-hashes.yml
    branches:
      - main

jobs:
  generate-hashes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Parse JSON
        run: jq . VERSION.json

      - name: Generate SHA-256 hashes
        run: |
          # Find all Python files
          find pyTGM/ -type f \( -name '*.py' -o -name '*.cpp' -o -name '*.hpp' -o -name '../setup-linux.sh' -o -name '../setup-win.sh' -o -name '../setup-mac.sh' -o -name '../setup.py' -o -name '../CMakeLists.txt' \) -print0 | xargs -0 sha256sum > hashes.txt

          # Ensure VERSION.json exists and has the 'hashes' object
          if [ ! -f VERSION.json ]; then
            echo '{"hashes":{}}' > VERSION.json
          fi

          # Update VERSION.json with the new hashes
          while IFS= read -r line; do
            file=$(echo "$line" | cut -d' ' -f2- | xargs)
            hash=$(echo "$line" | cut -d' ' -f1)
            jq ".hashes[\"$file\"] = \"$hash\"" VERSION.json > VERSION.json.tmp && mv VERSION.json.tmp VERSION.json
          done < hashes.txt

          # Delete hashes.txt after it is used
          rm hashes.txt

      - name: Check for changes in VERSION.json and setup.py
        run: |
          if git diff --quiet --exit-code VERSION.json setup.py; then
            echo "No changes to VERSION.json or any other places that have hashes, skipping commit."
            exit 0
          fi

      - name: Commit and Push Changes
        run: |
          git config --local user.name "TokynBlast"
          git config --local user.email "tokynblast@gmail.com"
          git add VERSION.json setup.py
          git commit --allow-empty -m "Update security hashes"
          git push
