name: Lint with Isort
on:
  push:
    paths:
      - pytgm/**
      - setup.py
      - .github/workflows/Isort.yml
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install Isort
        run: pip install isort
      - name: Run Isort
        run: isort *.py
