name: LicLock-Check

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  LicLockCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Check for LicLock
        run: |
          echo "Checking license Lock..."
          if [ -f ".github/LicLock"]; then
              echo "Doing nothing. LicLock found."
              exit 0
          else
              curl -o temp_lic.md https://raw.githubusercontent.com/TokynBlast/TBTemplate/refs/heads/main/LICENSE.md
              if ! diff temp_lic.md LICENSE.md; then
                  mv temp_lic.md LICENSE.md
                  rm temp_lic.md
                  git config user.name "GITHUB-ACTIONS-POTATO"
                  git config user.email "GitHub@po.tato"
                  git push
                  git commit -m "Updated Licence"
              fi
              exit 0
          fi
