name: Lint Python

on:
  push:
    branches:
      - main
    paths:
      - '**/*.cpp'
      - '**/*.hpp'
      - '**/*.h'
      - '**/CMakeLists.txt'
      - '.github/workflows/pylint.yml'
      - 'pyTGM/**'
      - '.pylintrc'
  pull_request:
    paths:
      - '**/*.cpp'
      - '**/*.hpp'
      - '**/*.h'
      - '**/CMakeLists.txt'
      - '.github/workflows/pylint.yml'
      - 'pyTGM/**'
      - '.pylintrc'

jobs:
  compile-and-lint:
    runs-on: ubuntu-24.04

    env:
      BUILT_MODULE: ${{ github.workspace }}/built_module
      STUBS: ${{ github.workspace }}/stubs
      PYTHONPATH: ${{ github.workspace }}/built_module

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel nanobind pylint mypy pip-audit

      - name: Get nanobind CMake directory
        id: nb
        run: echo "dir=$(python -m nanobind --cmake_dir)" >> $GITHUB_OUTPUT

      - name: Configure project with CMake
        run: |
          mkdir -p build
          cd build
          cmake .. \
            -DCMAKE_INSTALL_PREFIX="${BUILT_MODULE}" \
            -DPython_EXECUTABLE="$(which python)" \
            -DCMAKE_PREFIX_PATH="${{ steps.nb.outputs.dir }}"

      - name: Build and install
        run: |
          cmake --build build --config Release --target install

      - name: Run linters
        run: |
          unset PYTHONPATH
          pylint pyTGM
          mypy pyTGM

      - name: Audit Python dependencies
        run: |
          pip-audit
