name: Pylint

on:
  push:
    branches:
      - main
    paths:
      - "**/*.py"
      - "**/*.cpp"
      - "pyTGM/**"
      - ".github/workflows/pylint.yml"

jobs:
  compile-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pybind11 setuptools wheel pylint pybind11-stubgen

      - name: Compile C++ extension with g++
        run: |
          mkdir -p built_module
          SOURCES=$(find pyTGM -type f -name '*.cpp')
          echo "Compiling sources: $SOURCES"
          g++ -O3 -Wall -shared -std=c++17 -fPIC $(python -m pybind11 --includes) $SOURCES -o built_module/pyTGM$(python3-config --extension-suffix)

      - name: Generate stubs for pyTGM module
        run: |
          pybind11-stubgen pyTGM -o stubs
          echo "PYTHONPATH=$PYTHONPATH:$(pwd)/built_module:$(pwd)/stubs" >> $GITHUB_ENV

      - name: Run pylint on Python files
        run: |
          pylint $(git ls-files '*.py')
