name: Pylint

on:
  push:
    paths:
      - pytgm/**
      - setup.py
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install setuptools
        pip install pybind11
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
