name: Pylint

on:
  push:
    branches:
      - main
    paths:
      - "**/*.py"
      - "**/*.cpp"
      - "CMakeLists.txt"
      - ".github/workflows/pyTGM.yml"

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cmake pybind11 setuptools wheel pylint pybind11-stubgen

      - name: Compile C++ extension via CMake
        run: |
          mkdir -p build && cd build
          pybind11_DIR=$(python -m pybind11 --cmakedir)
          cmake -Dpybind11_DIR=${pybind11_DIR} -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --config Release --parallel

      - name: Install built module
        run: |
          mkdir -p built_module
          cp build/pyTGM*.so built_module/
          echo "PYTHONPATH=$PYTHONPATH:$(pwd)/built_module" >> $GITHUB_ENV

      - name: Generate stubs for pyTGM module
        run: |
          pybind11-stubgen pyTGM -o stubs
          echo "PYTHONPATH=$PYTHONPATH:$(pwd)/stubs" >> $GITHUB_ENV

      - name: Run pylint
        run: |
          pylint $(git ls-files '*.py')
