name: Pylint

on:
  push:
    branches:
      - main
    paths:
      - "**/*.py"
      - "**/*.cpp"
      - "pyTGM/**"
      - ".github/workflows/pylint.yml"

jobs:
  compile-and-lint:
    runs-on: ubuntu-latest
    env:
      # Set variables to point to our workspace subdirectories
      BUILT_MODULE: ${{ github.workspace }}/built_module
      STUBS: ${{ github.workspace }}/stubs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pybind11 pybind11-stubgen setuptools wheel pylint

      - name: Compile C++ extension with g++
        run: |
          mkdir -p built_module
          # Find all .cpp files under the pyTGM folder
          SOURCES=$(find pyTGM -type f -name '*.cpp')
          echo "Compiling sources: $SOURCES"
          # Compile all sources into one shared library
          g++ -O3 -Wall -shared -std=c++17 -fPIC $(python -m pybind11 --includes) $SOURCES -o built_module/pyTGM$(python3-config --extension-suffix)
          echo "Built module:"
          ls -la built_module/

      - name: Generate stubs for pyTGM module
        env:
          PYTHONPATH: ${{ github.workspace }}/built_module
        run: |
          echo "PYTHONPATH for stubgen is: $PYTHONPATH"
          pybind11-stubgen pyTGM -o stubs
          echo "Stubs generated:"
          ls -la stubs/

      - name: Run pylint on Python files
        env:
          PYTHONPATH: ${{ github.workspace }}/built_module:${{ github.workspace }}/stubs
        run: |
          pylint $(git ls-files '*.py')
