name: Security Check

on:
  push:
    paths:
      - pyTGM/**/*.py
      - .github/workflows/Security-Check.yml
      - 'requirements.txt'
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Install pip-audit
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit

      - name: Audit Python dependencies listed in requirements.txt
        run: |
          echo "Running pip-audit using requirements.txt..."
          if [ -f "requirements.txt" ]; then
            pip-audit -r requirements.txt || echo "pip-audit found issues (continuing build anyway)"
          else
            echo "No requirements.txt found. Skipping pip-audit."
          fi
