name: Security Check

on:
  push:
    paths:
      - pyTGM/**/*.py
      - .github/workflows/Saftey.yml
    branches:
      - main

jobs:
  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pip-audit
        run: pip install pip-audit

      - name: Run pip-audit
        run: pip-audit
      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit on code
        run: bandit -r pyTGM/
