name: Security Check

on:
  push:
    paths:
      - pyTGM/**/*.py
      - .github/workflows/Security-Check.yml
      - 'requirements.txt'
    branches:
      - main

jobs:
  security-scan:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      - name: Install required Python packages
        run: |
          python -m pip install --upgrade pip
          if [ -f "requirements.txt" ]; then
            echo "Found requirements.txt, installing from it."
            pip install -r requirements.txt
          else
            echo "No requirements.txt found, installing required packages manually if missing."
            REQUIRED_PACKAGES="setuptools wheel nanobind pylint mypy pip-audit"
            for PACKAGE in $REQUIRED_PACKAGES; do
              if ! python -c "import $PACKAGE" 2>/dev/null; then
                echo "Installing missing package: $PACKAGE"
                pip install "$PACKAGE"
              else
                echo "Package $PACKAGE already installed."
              fi
            done
          fi

      - name: Audit Python dependencies for vulnerabilities
        run: |
          echo "Running pip-audit..."
          pip-audit || echo "pip-audit found issues (continuing build anyway)"
