name: Python Test

on:
  push:
    paths:
      - '**/*.py'
      - '**/*.cpp'
      - '**/*.hpp'
      - 'CMakeLists.txt'
      - 'test.py'
      - 'setup.py'
      - '.github/workflows/test.yml'
  pull_request:
    paths:
      - '**/*.cpp'
      - '**/*.hpp'
      - 'CMakeLists.txt'
      - 'test.py'
      - 'setup.py'
      - 'pyproject.toml'
      - '.github/workflows/compile.yml'

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    timeout-minutes: 60  # Increase the timeout to 60 minutes
    env:
      ACTIONS_STEP_DEBUG: true  # Enable step debugging
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install system dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential python3-dev libasound2-dev

    - name: Install system dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install cmake

    - name: Install system dependencies (Windows)
      if: runner.os == 'Windows'
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' --yes

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nanobind setuptools wheel
        pip freeze  # Print installed packages to verify installation

    - name: Build and install the nanobind extension
      run: |
        for i in {1..3}; do
          python -m pip install . && break || sleep 15  # Retry up to 3 times if installation fails
        done

    - name: Run test script
      run: |
        python test.py
